package dev.michalak.adam.springstring.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.EqualsAndHashCode;

import java.util.List;


@Builder
// By default, constructor generated by Lombok is package-private.
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
@EqualsAndHashCode
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonDeserialize(builder = PalindromesRequest.PalindromesRequestBuilder.class)
public class PalindromesRequest {
    @JsonProperty
    private List<String> palindromes;
}
