package dev.michalak.adam.springstring.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.EqualsAndHashCode;

@Builder
// By default, constructor generated by Lombok is package-private.
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
@EqualsAndHashCode
public class StringAnalysisResponse {

    @JsonProperty("concatenated")
    @Builder.Default
    private final String concatenatedResult = "";

    @JsonProperty
    private final boolean palindromePresent;

    @JsonProperty
    private final double averageLength;
}
