package dev.michalak.adam.springstring.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.io.Serializable;

@Builder
// By default, constructor generated by Lombok is package-private.
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
@EqualsAndHashCode
public class StringResponse implements Serializable {
    // Required to verify that loaded class and the serialized object are compatible.
    private static final long serialVersionUID = 7654321L;

    @JsonProperty("concatenated")
    @Builder.Default
    private final String concatenatedResult = "";

    @JsonProperty("palindromePresent")
    private final boolean palindromePresent;

    @JsonProperty("averageLength")
    private final double averageLength;
}
