package dev.michalak.adam.springstring.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.io.Serializable;

@Builder
// By default, constructor generated by Lombok is package-private.
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class StringResponse implements Serializable {
    // Required to verify that loaded class and the serialized object are compatible.
    private static final long serialVersionUID = 7654321L;

    @JsonProperty("result")
    private final String result;
}
